### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by j-lang** [WebentwicklerAt/typo3-emogrifier#9]
The following error occurring since last security update 7.6.30: 
_Core: Error handler (FE): PHP Warning: file_exists(): open_basedir restriction in effect. File(/home/www/xxx/html/typo3/typo3conf/ext/emogrifier/Resources/Private/Php/Emogrifier.phar/vendor/autoload.php) is not within the allowed path(s): (/:/dev/urandom) in /html/typo3/typo3_src-7.6.30/typo3/sysext/core/Classes/IO/PharStreamWrapper.php line 454_  

Error is thrown by sending confirmation e-mail in seminars-extension (2.0.1) 
Changes of [https://review.typo3.org/#/c/57595/ ](url) do not solve the problem.

**References**
[https://get.typo3.org/release-notes/7.6.30](url) 
[https://review.typo3.org/#/c/57595/ ](url)

**Comment by j-lang** [comment]
Tested bugfix/phar version and **it works** again.

**Comment by leitgab** [comment]
As you mentioned in your issue description, the warning was introduced with the latest security fix of TYPO3 core with the introduction of `PharStreamWrapper`. Furthermore you mentioned, that the problem of phar inclusion in conjunction with `open_basedir` restriction was identified in TYPO3 core and a [bugfix](https://review.typo3.org/#/c/57595/) is in development. In theory, the provided bugfix should exactly address your issue and the mentioned warning should be suppressed by it. If you can provide a reasonable explanation, why the core-patch does not solve the issue for you, I will provide a patch version with the pull request thankfully provided by @oliverklee. Otherwise I will close this issue, because this problem has to be addressed and solved in TYPO3 core.

**Comment by leitgab** [comment]
With today's [releases](https://typo3.org/article/typo3-933-8718-and-7631-released/) your problem should be fixed in TYPO3 core. Therefore I close this issue.
